version: '3'

services:
    ad_nerf:
        container_name: ad_nerf
        image: opachoand/adnerf
        restart: 'no'
        volumes:
            - /home/opacho/Документы/GitHub/LEQ_service/cloud:/usr/src/app/cloud
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 5432:5432
    web_interface:
        container_name: web
        image: opachoand/web
        restart: always
        build: web_interface/
        volumes:
            - /home/opacho/Документы/GitHub/LEQ_service/cloud:/usr/src/app/cloud
        ports:
            - 8000:8000
    mq:
        container_name: rabbit_mq
        image: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
